flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")

flask_blog/main/routes.py
from flask import render_template, Blueprint

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template("home.html")

flask_blog/posts/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for, abort
from flask_login import login_required, current_user
from sqlalchemy import desc

from flask_blog import db
from flask_blog.models import Post
from .forms import PostForm

posts = Blueprint("posts", __name__)


@posts.route("/posts")
@login_required
def allposts():
    page = request.args.get("page", 1, type=int)
    ord_posts = Post.query.order_by(desc(Post.date_posted)).paginate(
        page=page, per_page=5
    )
    return render_template("posts.html", posts=ord_posts)


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post(
            title=form.title.data, content=form.content.data, author=current_user
        )
        db.session.add(new_post)
        db.session.commit()
        flash("Your post has been created!", "success")
        return redirect(url_for("posts.allposts"))
    return render_template(
        "create_post.html", title="New post", form=form, legend="New post"
    )


@posts.route("/post/<int:post_id>")
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.show_post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template(
        "create_post.html", title="Updating post", form=form, legend="Updating post"
    )


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for("posts.allposts"))

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password  # type: ignore
        )
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created, now you can log in", "success")

        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get("next")
            return (
                redirect(next_page)
                if next_page
                else redirect(url_for("posts.allposts"))
            )
        else:
            flash(
                "Couldn't sign in to the system. Please, check your email and password",
                "warning",
            )
    return render_template("login.html", title="Authentication", form=form)


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    else:
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get("page", 1, type=int)
        user = current_user
        posts = (
            Post.query.filter_by(author=user)
            .order_by(Post.date_posted)
            .paginate(page=page, per_page=5)
        )
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template(
        "account.html",
        title="Account",
        image_file=image_file,
        form=form,
        posts=posts,
        user=user,
    )


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = (
        Post.query.filter_by(author=user)
        .order_by(Post.date_posted)
        .paginate(page=page, per_page=5)
    )
    return render_template("user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("posts.allposts"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            "The instructions on how to change your password have been sent to your email address",
            "info",
        )
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset your password", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("posts.allposts"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("This token is invalid or has already expired.", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated! You can now authorize.", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset your password", form=form)

flask_blog/templates/account.html
{% extends "base.html" %}

{% block head %}
    <style>
        .container {
            margin-bottom: 0.8rem;
        }

        .content-section {
            box-shadow: 10px 20px 8px darkslategray;
        }

        .card {
            border-radius: 25px;
            /* border-top-right-radius: 25px;
            border-bottom-left-radius: 25px; */
            background-color: white;
            box-shadow: 10px 15px 10px #4a4e69;
            width: 92%;
        }

        a {
            color: #003049;
        }

        small {
            color: lightslategray;
        }

        p {
            color: rgb(43, 37, 37);
        }

        /* i{
          padding: 0px 7px;
          cursor: pointer;
        } */
    </style>
{% endblock head %}


{% block content %}
    <div class="content-section">
        <div class="media">
            {% if image_file %}
                <img class="rounded-circle account-img" src="{{ image_file }}" alt="profile picture">
            {% endif %}
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>

        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Your account</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>



{% endblock content %}

flask_blog/templates/base.html
<!DOCTYPE HTML>
<html lang="eng">

<head>
    <title>My Blog</title>
    <meta name="description" content="website description">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="/static/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>

<body>
<div id="main">
    <div id="header">
        <div id="logo">
            <div id="logo_text">
                <h1><a href="{{ url_for('main.home') }}">My Blog</a></h1>
                {% if current_user.is_authenticated %}
                    <h2>Hey, {{ current_user.username }}!</h2>
                {% endif %}
            </div>
        </div>
        <div id="menubar">
            <ul id="menu">
                <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
                <li><a href="{{ url_for('main.home') }}">HOME</a></li>
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('posts.allposts') }}">POSTS</a></li>
                    <li><a href="{{ url_for('users.user_posts', username=current_user.username) }}">YOUR POSTS</a></li>
                    <li><a href="{{ url_for('posts.create_post') }}">CREATE POST</a></li>
                    <li><a href="{{ url_for('users.account') }}">PROFILE</a></li>
                    <li><a href="{{ url_for('users.logout') }}">LOGOUT</a></li>
                {% else %}
                    <li><a href="{{ url_for('users.register') }}">SIGN UP</a></li>
                    <li><a href="{{ url_for('users.login') }}">SIGN IN</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div id="site_content">
        <div class="sidebar">
            <!-- insert your sidebar items here -->
            <h3>Latest News</h3>
            <h4>New Website Launched</h4>
            <h5>July 1st, 2014</h5>
            <p>2014 sees the redesign of our website. Take a look around and let us know what you think.<br/><a
                    href="#">Read more</a></p>
            <p></p>
            <h4>New Website Launched</h4>
            <h5>July 1st, 2014</h5>
            <p>2014 sees the redesign of our website. Take a look around and let us know what you think.<br/><a
                    href="#">Read more</a></p>
            <h3>Useful Links</h3>
            <ul>
                <li><a href="#">link 1</a></li>
                <li><a href="#">link 2</a></li>
                <li><a href="#">link 3</a></li>
                <li><a href="#">link 4</a></li>
            </ul>
            <h3>Search</h3>
            <form method="post" action="#" id="search_form">
                <p>
                    <label>
                        <input class="search" type="text" name="search_field" value="Enter keywords....."/>
                    </label>
                    <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;"
                           src="{{ url_for('static', filename='images/'+'search.png') }}"
                           alt="Search" title="Search"/>
                </p>
            </form>
        </div>
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-10">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}

                </div>
            </div>
        </main>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div id="footer">
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">

</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
        integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
        integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK"
        crossorigin="anonymous"></script>
</body>
</html>

flask_blog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to My Blog! Here's some info about this website: </h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad iure nemo perferendis tempora voluptate? A ad
        architecto, atque blanditiis debitis deleniti esse, ex in itaque libero magni maxime officiis possimus quis
        quisquam reiciendis repellat reprehenderit repudiandae sint tempore temporibus ullam vel veritatis? Amet aperiam
        consectetur consequuntur fuga illum ipsa magnam, nam nemo praesentium reprehenderit veniam voluptate voluptatem
        voluptates! A accusamus amet architecto asperiores aspernatur cum cumque distinctio enim est eum explicabo
        facere harum id impedit inventore laboriosam laborum maxime minima molestias mollitia nam nisi obcaecati, odio
        odit officiis perspiciatis quia recusandae repellat saepe sapiente tempore totam veritatis voluptatum? Rem,
        totam!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto asperiores aut delectus dicta ducimus earum
        impedit in iste iure libero molestiae natus, nemo possimus quam quod reiciendis rem sequi sint?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet, optio?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis delectus et hic neque nostrum quam quia,
        reiciendis similique sunt tempora.</p>
    <h2>Lorem ipsum.</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem, modi.</p>
    <ul>
        <li>Lorem ipsum dolor.</li>
        <li>Lorem ipsum dolor.</li>
        <li>Lorem ipsum dolor.</li>
    </ul>
{% endblock %}

flask_blog/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Authorization</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
            <small style="font-size: 15px; font-weight: 500;">
                <a class="ml-2" href="{{ url_for('users.register') }}">Sign up if you don't have an account</a>
            </small>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/post.html
{% extends "base.html" %}

{% block head %}
    <style>
        .container {
            margin-bottom: 0.8rem;
        }

        .card {
            border-radius: 25px;
            background-color: white;
            box-shadow: 10px 15px 10px #4a4e69;
            width: 92%;
        }

        .card-title {
            margin-bottom: 0 !important;
            font-family: 'Bebas Neue', cursive;
        }

        a {
            color: #003049 !important;
            text-decoration: none;
        }

        small {
            color: lightslategray;
        }

        p {
            color: rgb(43, 37, 37);
        }

    </style>
{% endblock head %}

{% block content %}
    <div class="container" style="display: flex;">
        <article class="media" style="display: flex; flex-direction: column;">
            <img class="rounded-circle article-img" style="margin-right: 5px;"
                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
               style="margin: 0 auto">{{ post.author.username }}</a>
        </article>
        <div class="card" style="margin-bottom: 20px;">
            <div class="card-body">
                <h4 class="card-title">{{ post.title }}</h4>
                <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                <br>
                <br>
                <p class="card-text">{{ post.content }}</p>
            </div>
            <div class="card-footer" style="font-size: 20px;">
                {% if post.author == current_user %}
                    <div class="card-footer" style="font-size: 20px;">
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
                                data-bs-target="#exampleModal">
                            Delete
                        </button>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete this post?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

flask_blog/templates/posts.html
{% extends "base.html" %}

{% block head %}
    <style>
        .card {
            border-radius: 25px;
            background-color: white;
            box-shadow: 10px 15px 10px #4a4e69;
            width: 92%;
        }

        a {
            color: #003049 !important;
            text-decoration: none;
        }

        small {
            color: lightslategray;
        }

        p {
            color: rgb(43, 37, 37);
        }

    </style>
{% endblock head %}

{% block content %}
    {% for post in posts.items %}
        <div class="container" style="display: flex;">
            <article class="media" style="display: flex; flex-direction: column;">
                <img class="rounded-circle article-img" style="margin-right: 5px;"
                     src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="pfp">
                <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author"
                   style="margin: 0 auto;">{{ post.author.username }}</a>
            </article>

            <div class="card" style="margin-bottom: 20px;">
                <div class="card-body">
                    <h4 class="card-title">
                        <a class="title" href="{{ url_for('posts.show_post', post_id=post.id) }}">{{ post.title }}</a>
                    </h4>
                    <small>Published {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                    <br>
                    <br>
                    <p class="card-text">{{ post.content }}</p>
                </div>
            </div>
        </div>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-success mb-4" href="{{ url_for('posts.allposts', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-success mb-4"
                   href="{{ url_for('posts.allposts', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flask_blog/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset your password</legend>
                <div class="form-group">
                    <legend class="mb-4">Enter your user account's verified email address and we will send
                        you a password reset link.
                    </legend>
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/user_posts.html
{% extends "base.html" %}

{% block head %}
    <style>
        .container {
            margin-bottom: 0.8rem;
        }

        .card {
            border-radius: 25px;
            background-color: white;
            box-shadow: 10px 15px 10px #4a4e69;
            width: 92%;
        }

        .card-title {
            margin-bottom: 0 !important;
            font-family: 'Bebas Neue', cursive;
        }

        a {
            color: #003049 !important;
            text-decoration: none;
        }

        small {
            color: lightslategray;
        }

        p {
            color: rgb(43, 37, 37);
        }

    </style>
{% endblock head %}

{% block content %}
    <h1 class="mb-3">Posts published by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <div class="container" style="display: flex;">
            <article class="media" style="display: flex; flex-direction: column;">
                <img class="rounded-circle article-img" style="margin-right: 5px;"
                     src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
                   style="margin: 0 auto">{{ post.author.username }}</a>
            </article>

            <div class="card" style="margin-bottom: 20px;">
                <div class="card-body">
                    <h4 class="card-title">
                        <a class="title" href="{{ url_for('posts.show_post', post_id=post.id) }}">{{ post.title }}</a>
                    </h4>

                    <small>Published on
                        {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                    <br>
                    <br>
                    <p class="card-text">{{ post.content }}</p>
                </div>
            </div>
        </div>
    {% endfor %}


    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-success mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-success mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}